---
micronaut:
  application:
    name: training-video-player

---
micronaut:
  router:
    static:
      resources:
        enabled: true

micronaut.router.static-resources:
  webjars:
    paths: classpath:META-INF/resources/webjars
    mapping: /webjars/**
  css:
    paths: classpath:/css
    mapping: /css/**
  js:
    paths: classpath:/js
    mapping: /js/**
---
micronaut.views.thymeleaf.enabled: true
---
micronaut:
  metrics:
    enabled: true

---
micronaut:
  io:
    watch:
      paths: src/main
      restart: true
---
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1

---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
